# Generated by Django 2.1.15 on 2020-09-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEspecialidad', models.IntegerField()),
                ('nombreEspecialidad', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idLocalidad', models.IntegerField()),
                ('nombreLocalidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sqlserverconn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePrestador', models.CharField(max_length=500)),
                ('nombreEspecialidad', models.CharField(max_length=200)),
                ('direccionPrestador', models.CharField(max_length=500)),
                ('telefonoPrestador', models.CharField(max_length=20)),
                ('localidadPrestador', models.CharField(max_length=50)),
                ('provinciaPrestador', models.CharField(max_length=50)),
            ],
        ),
    ]
