# Generated by Django 2.1.15 on 2020-10-01 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlserverconn',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='fav_prestador', to=settings.AUTH_USER_MODEL),
        ),
    ]
